Response {
  robot:
   Robot {
     adapterPath: '/Users/ms0202/Desktop/rooming_bot/rooming-bot/node_modules/hubot/src/adapters',
     name: 'rooming-hubot',
     events:
      EventEmitter {
        domain: null,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined },
     brain:
      Brain {
        data: [Object],
        autoSave: false,
        saveInterval: [Object],
        _events: [Object],
        _eventsCount: 2 },
     alias: false,
     adapter:
      SlackBot {
        robot: [Circular],
        options: [Object],
        reaction: [Function],
        message: [Function],
        error: [Function],
        close: [Function],
        authenticated: [Function],
        open: [Function],
        client: [Object],
        _events: {},
        _eventsCount: 0,
        self: [Object] },
     Response: [Function: Response],
     commands:
      [ 'hubot ping - Reply with pong',
        'hubot adapter - Reply with the adapter',
        'hubot echo <text> - Reply back with <text>',
        'hubot time - Reply with current time',
        'hubot help - Displays all of the help commands that Hubot knows about.',
        'hubot help <query> - Displays all help commands that match <query>.',
        'hubot image me <query> - The Original. Queries Google Images for <query> and returns a random top result.',
        'hubot animate me <query> - The same thing as `image me`, except adds a few parameters to try to return an animated GIF instead.',
        'hubot mustache me <url|query> - Adds a mustache to the specified URL or query result.',
        'hubot translate me <phrase> - Searches for a translation for the <phrase> and then prints that bad boy out.',
        'hubot translate me from <source> into <target> <phrase> - Translates <phrase> from <source> into <target>. Both <source> and <target> are optional',
        'hubot pug me - Receive a pug',
        'hubot pug bomb N - get N pugs',
        'hubot map me <query> - Returns a map view of the area returned by `query`.',
        'hubot the rules - Make sure hubot still knows the rules.',
        'ship it - Display a motivation squirrel' ],
     listeners:
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     middleware: { listener: [Object], response: [Object], receive: [Object] },
     logger: EventEmitter { level: 6, stream: [Object] },
     pingIntervalId: null,
     globalHttpOptions: {},
     version: '2.19.0',
     server:
      Server {
        domain: null,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        _connections: 0,
        _handle: [Object],
        _usingSlaves: false,
        _slaves: [],
        _unref: false,
        allowHalfOpen: true,
        pauseOnConnect: false,
        httpAllowHalfOpen: false,
        timeout: 120000,
        _pendingResponseData: 0,
        _connectionKey: '4:0.0.0.0:8080' },
     router:
      { [Function: app]
        use: [Function],
        handle: [Function],
        listen: [Function],
        domain: undefined,
        _events: [Object],
        _maxListeners: undefined,
        setMaxListeners: [Function: setMaxListeners],
        getMaxListeners: [Function: getMaxListeners],
        emit: [Function: emit],
        addListener: [Function: addListener],
        on: [Function: addListener],
        once: [Function: once],
        removeListener: [Function: removeListener],
        removeAllListeners: [Function: removeAllListeners],
        listeners: [Function: listeners],
        listenerCount: [Function: listenerCount],
        route: '/',
        stack: [Object],
        init: [Function],
        defaultConfiguration: [Function],
        engine: [Function],
        param: [Function],
        set: [Function],
        path: [Function],
        enabled: [Function],
        disabled: [Function],
        enable: [Function],
        disable: [Function],
        configure: [Function],
        acl: [Function],
        bind: [Function],
        checkout: [Function],
        connect: [Function],
        copy: [Function],
        delete: [Function],
        get: [Function],
        head: [Function],
        link: [Function],
        lock: [Function],
        'm-search': [Function],
        merge: [Function],
        mkactivity: [Function],
        mkcalendar: [Function],
        mkcol: [Function],
        move: [Function],
        notify: [Function],
        options: [Function],
        patch: [Function],
        post: [Function],
        propfind: [Function],
        proppatch: [Function],
        purge: [Function],
        put: [Function],
        rebind: [Function],
        report: [Function],
        search: [Function],
        subscribe: [Function],
        trace: [Function],
        unbind: [Function],
        unlink: [Function],
        unlock: [Function],
        unsubscribe: [Function],
        all: [Function],
        del: [Function],
        render: [Function],
        request: [Object],
        response: [Object],
        cache: {},
        settings: [Object],
        engines: {},
        _eventsCount: 1,
        _router: [Object],
        routes: [Object],
        router: [Getter],
        locals: [Object],
        _usedRouter: true },
     adapterName: 'slack',
     errorHandlers: [],
     onUncaughtException: [Function] },
  message:
   TextMessage {
     user:
      User {
        _properties: [Object],
        _modelName: 'User',
        id: 'U2DBEVB4M',
        team_id: 'T026QPGMQ',
        name: 'ludueno.lucas',
        deleted: false,
        status: null,
        color: 'de5f24',
        real_name: 'Lucas Ludueño',
        tz: 'America/Cayenne',
        tz_label: 'French Guiana Time',
        tz_offset: -10800,
        profile: [Object],
        is_admin: false,
        is_owner: false,
        is_primary_owner: false,
        is_restricted: false,
        is_ultra_restricted: false,
        is_bot: false,
        presence: 'active',
        room: 'D30CJCGBS' },
     text: 'rooming-hubot room 2',
     id: '1478986029.000048',
     done: false,
     room: 'D30CJCGBS' },
  match: [ 'room 2', index: 14, input: 'rooming-hubot room 2' ],
  envelope:
   { room: 'D30CJCGBS',
     user:
      User {
        _properties: [Object],
        _modelName: 'User',
        id: 'U2DBEVB4M',
        team_id: 'T026QPGMQ',
        name: 'ludueno.lucas',
        deleted: false,
        status: null,
        color: 'de5f24',
        real_name: 'Lucas Ludueño',
        tz: 'America/Cayenne',
        tz_label: 'French Guiana Time',
        tz_offset: -10800,
        profile: [Object],
        is_admin: false,
        is_owner: false,
        is_primary_owner: false,
        is_restricted: false,
        is_ultra_restricted: false,
        is_bot: false,
        presence: 'active',
        room: 'D30CJCGBS' },
     message:
      TextMessage {
        user: [Object],
        text: 'rooming-hubot room 2',
        id: '1478986029.000048',
        done: false,
        room: 'D30CJCGBS' } } }